### ISSUE TITLE
Error when using useMediaQuery with SSR

### ISSUE THREAD

**Issue by Kyzegs** [react-hookz/web#1039]
### Prior Issues

N\A

### What is the current behavior?

Throw an error.

### Steps to Reproduce

I don't have an environment with the error right now. I can try to create one if necessary.

```
ReferenceError: matchMedia is not defined
    at createQueryEntry (D:\Insync\Projects\Illustrator\GitHub\illustrator-web\node_modules\.pnpm\@react-hookz+web@20.0.0_biqbaboplfbrettd7655fr4n2y\node_modules\@react-hookz\web\cjs\useMediaQuery\useMediaQuery.js:7:15)
    at D:\Insync\Projects\Illustrator\GitHub\illustrator-web\node_modules\.pnpm\@react-hookz+web@20.0.0_biqbaboplfbrettd7655fr4n2y\node_modules\@react-hookz\web\cjs\useMediaQuery\useMediaQuery.js:61:25
    at useReducer (D:\Insync\Projects\Illustrator\GitHub\illustrator-web\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server-legacy.node.development.js:5083:57)
    at Object.useState (D:\Insync\Projects\Illustrator\GitHub\illustrator-web\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server-legacy.node.development.js:5021:10)
    at useState (D:\Insync\Projects\Illustrator\GitHub\illustrator-web\node_modules\.pnpm\react@18.2.0\node_modules\react\cjs\react.development.js:1622:21)
    at useMediaQuery (D:\Insync\Projects\Illustrator\GitHub\illustrator-web\node_modules\.pnpm\@react-hookz+web@20.0.0_biqbaboplfbrettd7655fr4n2y\node_modules\@react-hookz\web\cjs\useMediaQuery\useMediaQuery.js:56:35)
    at Navigation (file:///D:/Insync/Projects/Illustrator/GitHub/illustrator-web/bootstrap/ssr/assets/NavigationProfile.3973df05.mjs:57:26)
    at renderWithHooks (D:\Insync\Projects\Illustrator\GitHub\illustrator-web\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server-legacy.node.development.js:5662:16)
    at renderIndeterminateComponent (D:\Insync\Projects\Illustrator\GitHub\illustrator-web\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server-legacy.node.development.js:5735:15)
    at renderElement (D:\Insync\Projects\Illustrator\GitHub\illustrator-web\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server-legacy.node.development.js:5950:7)
```

### What is the expected behavior?

That `useMediaQuery` works with SSR enabled.

### Environment Details

- _`@react-hookz/web` version:_ 20.0.0
- _`react` version:_ 18.2.0
- _`react-dom` version:_ 18.2.0
- _`typescript` version:_ 4.9.3
- _OS:_ Windows 10
- _Browser:_ Chrome - Version 108.0.5359.94 (Official Build) (64-bit)
- _Did this work in previous versions?_ Yes

**Comment by xobotyi** [comment]
Do you pass `initializeWithValue: false`option? It has been introduced in 20.0.0 and described in changelog and docs.

**Comment by xobotyi** [comment]
You should have hydration error this way🤔

**Comment by proninyaroslav** [comment]
> Do you pass `initializeWithValue: false`option? It has been introduced in 20.0.0 and described in changelog and docs.

Works fine on NextJS 13
