### ISSUE TITLE
Port remaining hooks from `react-use`

### ISSUE THREAD

**Issue by JoeDuncko** [react-hookz/web#33]
Our goal with `@react-hookz/web` is to give the react community a general-purpose React hooks library built with care.

We'd like to port the remaining hooks from [react-use](https://github.com/streamich/react-use) (the project `@react-hookz/web` grew out of) while keeping in mind our tenants:

- General-purposeness (hooks should fulfill a wide array of use cases)
- Composability (a preference for hooks that are useful for building other hooks)
- No or _very few_ dependencies
- SSR compatibility
- 100% test coverage (ideally)
- Concrete example use cases

### Sensors

- [ ] [useBattery](https://github.com/streamich/react-use/blob/master/docs/useBattery.md) — tracks device battery state. 
- [ ] [useGeolocation](https://github.com/streamich/react-use/blob/master/docs/useGeolocation.md) — tracks geo location state of user's device. 
- [ ] [useHover](https://github.com/streamich/react-use/blob/master/docs/useHover.md) and useHoverDirty — tracks mouse hover state of some element. 
- [ ] [useHash](https://github.com/streamich/react-use/blob/master/docs/useHash.md) — tracks location hash value. 
- [ ] [useIdle](https://github.com/streamich/react-use/blob/master/docs/useIdle.md) — tracks whether user is being inactive.
- [ ] [useIntersection](https://github.com/streamich/react-use/blob/master/docs/useIntersection.md) — tracks an HTML element's intersection. 
- [ ] [useKey](https://github.com/streamich/react-use/blob/master/docs/useKey.md), useKeyPress, useKeyboardJs, and useKeyPressEvent — track keys. 
- [ ] [useLocation](https://github.com/streamich/react-use/blob/master/docs/useLocation.md) and useSearchParam — tracks page navigation bar location state.
- [ ] [useLongPress](https://github.com/streamich/react-use/blob/master/docs/useLongPress.md) — tracks long press gesture of some element.
- [ ] [useMedia](https://github.com/streamich/react-use/blob/master/docs/useMedia.md) — tracks state of a CSS media query. 
- [ ] [useMediaDevices](https://github.com/streamich/react-use/blob/master/docs/useMediaDevices.md) — tracks state of connected hardware devices.
- [ ] [useMotion](https://github.com/streamich/react-use/blob/master/docs/useMotion.md) — tracks state of device's motion sensor.
- [ ] [useMouse](https://github.com/streamich/react-use/blob/master/docs/useMouse.md) and useMouseHovered — tracks state of mouse position. 
- [ ] [useMouseWheel](https://github.com/streamich/react-use/blob/master/docs/useMouseWheel.md) — tracks deltaY of scrolled mouse wheel. 
- [ ] [useNetworkState](https://github.com/streamich/react-use/blob/master/docs/useNetworkState.md) — tracks the state of browser's network connection. 
- [ ] [useOrientation](https://github.com/streamich/react-use/blob/master/docs/useOrientation.md) — tracks state of device's screen orientation.
- [ ] [usePageLeave](https://github.com/streamich/react-use/blob/master/docs/usePageLeave.md) — triggers when mouse leaves page boundaries.
- [ ] [useScratch](https://github.com/streamich/react-use/blob/master/docs/useScratch.md) — tracks mouse click-and-scrub state.
- [ ] [useScroll](https://github.com/streamich/react-use/blob/master/docs/useScroll.md) — tracks an HTML element's scroll position. 
- [ ] [useScrolling](https://github.com/streamich/react-use/blob/master/docs/useScrolling.md) — tracks whether HTML element is scrolling.
- [ ] [useStartTyping](https://github.com/streamich/react-use/blob/master/docs/useStartTyping.md) — detects when user starts typing.
- [ ] [useWindowScroll](https://github.com/streamich/react-use/blob/master/docs/useWindowScroll.md) — tracks Window scroll position. 
- [ ] [useWindowSize](https://github.com/streamich/react-use/blob/master/docs/useWindowSize.md) — tracks Window dimensions. 
- [ ] [useMeasure](https://github.com/streamich/react-use/blob/master/docs/useMeasure.md) and useSize — tracks an HTML element's dimensions. 
- [ ] [createBreakpoint](https://github.com/streamich/react-use/blob/master/docs/createBreakpoint.md) — tracks innerWidth
- [ ] [useScrollbarWidth](https://github.com/streamich/react-use/blob/master/docs/useScrollbarWidth.md) — detects browser's native scrollbars width. 

### UI

- [ ] [useAudio](https://github.com/streamich/react-use/blob/master/docs/useAudio.md) — plays audio and exposes its controls. 
- [ ] [useClickAway](https://github.com/streamich/react-use/blob/master/docs/useClickAway.md) — triggers callback when user clicks outside target area.
- [ ] [useCss](https://github.com/streamich/react-use/blob/master/docs/useCss.md) — dynamically adjusts CSS.
- [ ] [useDrop](https://github.com/streamich/react-use/blob/master/docs/useDrop.md) and useDropArea — tracks file, link and copy-paste drops.
- [ ] [useFullscreen](https://github.com/streamich/react-use/blob/master/docs/useFullscreen.md) — display an element or video full-screen. 
- [ ] [useSlider](https://github.com/streamich/react-use/blob/master/docs/useSlider.md) — provides slide behavior over any HTML element. 
- [ ] [useSpeech](https://github.com/streamich/react-use/blob/master/docs/useSpeech.md) — synthesizes speech from a text string. 
- [ ] [useVibrate](https://github.com/streamich/react-use/blob/master/docs/useVibrate.md) — provide physical feedback using the Vibration API. 
- [ ] [useVideo](https://github.com/streamich/react-use/blob/master/docs/useVideo.md) — plays video, tracks its state, and exposes playback controls. 

### Animations

- [ ] [useRaf](https://github.com/streamich/react-use/blob/master/docs/useRaf.md) — re-renders component on each requestAnimationFrame.
- [ ] [useInterval](https://github.com/streamich/react-use/blob/master/docs/useInterval.md) and useHarmonicIntervalFn — re-renders component on a set interval using setInterval.
- [ ] [useSpring](https://github.com/streamich/react-use/blob/master/docs/useSpring.md) — interpolates number over time according to spring dynamics.
- [ ] [useTimeout](https://github.com/streamich/react-use/blob/master/docs/useTimeout.md) — re-renders component after a timeout.
- [ ] [useTimeoutFn](https://github.com/streamich/react-use/blob/master/docs/useTimeoutFn.md) — calls given function after a timeout. 
- [ ] [useTween](https://github.com/streamich/react-use/blob/master/docs/useTween.md) — re-renders component, while tweening a number from 0 to 1. 
- [x] [useUpdate](https://github.com/streamich/react-use/blob/master/docs/useUpdate.md) — returns a callback, which re-renders component when called.  (Implemented as [useUpdateEffect](https://react-hookz.github.io/web/?path=/docs/lifecycle-useUpdateEffect))

### Side-effects

- [ ] [useAsync](https://github.com/streamich/react-use/blob/master/docs/useAsync.md), useAsyncFn, and useAsyncRetry — resolves an async function.
- [ ] [useBeforeUnload](https://github.com/streamich/react-use/blob/master/docs/useBeforeUnload.md) — shows browser alert when user try to reload or close the page.
- [ ] [useCookie](https://github.com/streamich/react-use/blob/master/docs/useCookie.md) — provides way to read, update and delete a cookie. 
- [ ] [useCopyToClipboard](https://github.com/streamich/react-use/blob/master/docs/useCopyToClipboard.md) — copies text to clipboard.
- [ ] [useDebounce](https://github.com/streamich/react-use/blob/master/docs/useDebounce.md) — debounces a function. 
- [ ] [useError](https://github.com/streamich/react-use/blob/master/docs/useError.md) — error dispatcher. 
- [ ] [useFavicon](https://github.com/streamich/react-use/blob/master/docs/useFavicon.md) — sets favicon of the page.
- [ ] [useLocalStorage](https://github.com/streamich/react-use/blob/master/docs/useLocalStorage.md) — manages a value in localStorage.
- [ ] [useLockBodyScroll](https://github.com/streamich/react-use/blob/master/docs/useLockBodyScroll.md) — lock scrolling of the body element.
- [ ] [useRafLoop](https://github.com/streamich/react-use/blob/master/docs/useRafLoop.md) — calls given function inside the RAF loop.
- [ ] [useSessionStorage](https://github.com/streamich/react-use/blob/master/docs/useSessionStorage.md) — manages a value in sessionStorage.
- [ ] [useThrottle](https://github.com/streamich/react-use/blob/master/docs/useThrottle.md) and useThrottleFn — throttles a function. 
- [ ] [useTitle](https://github.com/streamich/react-use/blob/master/docs/useTitle.md) — sets title of the page.
- [ ] [usePermission](https://github.com/streamich/react-use/blob/master/docs/usePermission.md) — query permission status for browser APIs.

### Lifecycles

- [ ] [useEffectOnce](https://github.com/streamich/react-use/blob/master/docs/useEffectOnce.md) — a modified useEffect hook that only runs once.
- [ ] [useEvent](https://github.com/streamich/react-use/blob/master/docs/useEvent.md) — subscribe to events.
- [ ] [useLifecycles](https://github.com/streamich/react-use/blob/master/docs/useLifecycles.md) — calls mount and unmount callbacks.
- [x] [useMountedState](https://github.com/streamich/react-use/blob/master/docs/useMountedState.md) and useUnmountPromise — track if component is mounted. (Implemented as [useIsMounted](https://react-hookz.github.io/web/?path=/docs/lifecycle-useIsMounted))
- [ ] [usePromise](https://github.com/streamich/react-use/blob/master/docs/usePromise.md) — resolves promise only while component is mounted.
- [ ] [useLogger](https://github.com/streamich/react-use/blob/master/docs/useLogger.md) — logs in console as component goes through life-cycles.
- [x] [useMount](https://github.com/streamich/react-use/blob/master/docs/useMount.md) — calls mount callbacks. (Implemented as [useMountEffect](https://react-hookz.github.io/web/?path=/docs/lifecycle-useMountEffect))
- [x] [useUnmount](https://github.com/streamich/react-use/blob/master/docs/useUnmount.md) — calls unmount callbacks. (Implemented as [useUnmountEffect](https://react-hookz.github.io/web/?path=/docs/lifecycle-useUnmountEffect))
- [ ] [useUpdateEffect](https://github.com/streamich/react-use/blob/master/docs/useUpdateEffect.md) — run an effect only on updates.
- [ ] [useIsomorphicLayoutEffect](https://github.com/streamich/react-use/blob/master/docs/useIsomorphicLayoutEffect.md) — useLayoutEffect that does not show warning when server-side rendering.
- [ ] [useDeepCompareEffect](https://github.com/streamich/react-use/blob/master/docs/useDeepCompareEffect.md), useShallowCompareEffect, and useCustomCompareEffect — run an effect depending on deep comparison of its dependencies

### State

- [ ] [createMemo](https://github.com/streamich/react-use/blob/master/docs/createMemo.md) — factory of memoized hooks.
- [ ] [createReducer](https://github.com/streamich/react-use/blob/master/docs/createReducer.md) — factory of reducer hooks with custom middleware.
- [ ] [createReducerContext](https://github.com/streamich/react-use/blob/master/docs/createReducerContext.md) and createStateContext — factory of hooks for a sharing state between components.
- [ ] [useDefault](https://github.com/streamich/react-use/blob/master/docs/useDefault.md) — returns the default value when state is null or undefined.
- [ ] [useGetSet](https://github.com/streamich/react-use/blob/master/docs/useGetSet.md) — returns state getter get() instead of raw state.
- [ ] [useGetSetState](https://github.com/streamich/react-use/blob/master/docs/useGetSetState.md) — as if useGetSet and useSetState had a baby.
- [ ] [useLatest](https://github.com/streamich/react-use/blob/master/docs/useLatest.md) — returns the latest state or props
- [x] [usePrevious](https://github.com/streamich/react-use/blob/master/docs/usePrevious.md) — returns the previous state or props. (Implemented as [usePrevious](https://react-hookz.github.io/web/?path=/docs/lifecycle-usePrevious))
- [ ] [usePreviousDistinct](https://github.com/streamich/react-use/blob/master/docs/usePreviousDistinct.md) — like usePrevious but with a predicate to determine if previous should update.
- [ ] [useObservable](https://github.com/streamich/react-use/blob/master/docs/useObservable.md) — tracks latest value of an Observable.
- [ ] [useRafState](https://github.com/streamich/react-use/blob/master/docs/useRafState.md) — creates setState method which only updates after requestAnimationFrame. 
- [ ] [useSetState](https://github.com/streamich/react-use/blob/master/docs/useSetState.md) — creates setState method which works like this.setState. 
- [ ] [useStateList](https://github.com/streamich/react-use/blob/master/docs/useStateList.md) — circularly iterates over an array. 
- [x] [useToggle](https://github.com/streamich/react-use/blob/master/docs/useToggle.md) and useBoolean — tracks state of a boolean. (Implemented as [useToggle](https://react-hookz.github.io/web/?path=/docs/lifecycle-useToggle))
- [ ] [useCounter](https://github.com/streamich/react-use/blob/master/docs/useCounter.md) and useNumber — tracks state of a number. 
- [ ] [useList](https://github.com/streamich/react-use/blob/master/docs/useList.md) and useUpsert — tracks state of an array. 
- [ ] [useMap](https://github.com/streamich/react-use/blob/master/docs/useMap.md) — tracks state of an object. 
- [ ] [useSet](https://github.com/streamich/react-use/blob/master/docs/useSet.md) — tracks state of a Set. 
- [ ] [useQueue](https://github.com/streamich/react-use/blob/master/docs/useQueue.md) — implements simple queue.
- [ ] [useStateValidator](https://github.com/streamich/react-use/blob/master/docs/useStateValidator.md) — tracks state of an object. 
- [ ] [useStateWithHistory](https://github.com/streamich/react-use/blob/master/docs/useStateWithHistory.md) — stores previous state values and provides handles to travel through them. 
- [ ] [useMultiStateValidator](https://github.com/streamich/react-use/blob/master/docs/useMultiStateValidator.md) — alike the useStateValidator, but tracks multiple states at a time. 
- [x] [useMediatedState](https://github.com/streamich/react-use/blob/master/docs/useMediatedState.md) — like the regular useState but with mediation by custom function. (Implemented as [useMediatedState](https://react-hookz.github.io/web/?path=/docs/lifecycle-usemediatedstate))
- [x] [useFirstMountState](https://github.com/streamich/react-use/blob/master/docs/useFirstMountState.md) — check if current render is first. (Implemented as [useFirstMountState](https://react-hookz.github.io/web/?path=/docs/lifecycle-usefirstmountstate))
- [ ] [useRendersCount](https://github.com/streamich/react-use/blob/master/docs/useRendersCount.md) — count component renders. 
- [ ] [createGlobalState](https://github.com/streamich/react-use/blob/master/docs/createGlobalState.md) — cross component shared state.
- [ ] [useMethods](https://github.com/streamich/react-use/blob/master/docs/useMethods.md) — neat alternative to useReducer. 

### Miscellaneous

- [ ] [useEnsuredForwardedRef](https://github.com/streamich/react-use/blob/master/docs/useEnsuredForwardedRef.md) and ensuredForwardRef — use a React.forwardedRef safely. 

## Join our community!

Have a question? [Create a discussion on GitHub](https://github.com/react-hookz/web/discussions) or [join our Discord community](https://discord.gg/g98vMASa).

Interested in contributing code? Check out our [contribution guide](https://github.com/react-hookz/web/blob/master/CONTRIBUTING.md). We are excited to see your pull request!

**Comment by xobotyi** [comment]
To be clear - not all hooks will be ported, as for me - i'm against of transfering all `create*` hooks. And its not the only example.

**Comment by JoeDuncko** [comment]
> To be clear - not all hooks will be ported, as for me - i'm against of transfering all `create*` hooks. And its not the only example.

Definitely! Should we make a list of all the hooks that we don't want ported? Then I can cross them out above. @xobotyi

**Comment by xobotyi** [comment]
@JoeDuncko its hard to say rn, im reviewing the hooks on the go and currently refactoring (the full cycle refactoring, meaning reimplementing the from the scratch) hooks im currently using at my job, as this is easiest way for me, as i have little expertise in other areas.

**Comment by xobotyi** [comment]
>useMountedState and useUnmountPromise — track if component is mounted. (Implemented as useIsMounted)
we dont have `useUnmountPromise` yet

**Comment by JoeDuncko** [comment]
Crossed out the "create" hooks, split up all the lines with "and"s.

**Comment by JoeDuncko** [comment]
Added links to the new `useIsomorphicLayoutEffect` and `useDebounceCallback` hooks

**Comment by axelboc** [comment]
Thank you so much for starting this repo and leading this huge migration work! 🍻 

Just wondering what the reasoning is for not migrating the `create*` utilities, and particularly `createMemo`. In my project, I have a good number of utility functions that loop over very large arrays, so it's important that they are memoised with `useMemo`. With `createMemo` I don't have to create hooks with the same signature as the utility functions, so it's really convenient and avoids a lot of duplication (especially since I use TypeScript).

**Comment by JoeDuncko** [comment]
This issue should now be up to date FYI.

**Comment by hedgerh** [comment]
It'd be nice to know what needs to be done to port a hook over.  I'd like to port `useCopyToClipboard`, but I'm not sure if it needs refactoring.

Should it keep using `useSetState`? Can `useSetState` be ported over as-is?  It also needs to use `useIsMounted` instead of `useMountedState`.  What else?

I wouldn't mind helping out with stories/docs so someone with more context could focus on writing/porting the hooks.

**Comment by xobotyi** [comment]
@hedgerh it can't be ported as-is since it's dependency (clipboardjs) should be listed as optional depency now (look at useCookie to see how package check implemented).
Tbh I don't remember all internals and away from pc, I'll reply to you once I'll reach the laptop.

**Comment by hedgerh** [comment]
No rush. Why are these being listed as peerdeps and as optional now?

**Comment by xobotyi** [comment]
@hedgerh since very few people need these hooks - there is no need to make everyone to download them.

**Comment by xobotyi** [comment]
@hedgerh since very few people need these hooks - there is no need to make everyone to download them.

**Comment by Rey-Wang** [comment]
@xobotyi I'm wondering are going to implement the `useCustomCompareEffect` |`useDeepCompareEffect` hook?

**Comment by xobotyi** [comment]
@Rey-Wang working on it right now, will be published Monday I guess

**Comment by JoeDuncko** [comment]
This issue is now up to date.

@Rey-Wang we now have `useCustomCompareEffect` and `useDeepCompareEffect`!

**Comment by kylemh** [comment]
`usePreviousDistinct` done ✅

**Comment by JoeDuncko** [comment]
> `usePreviousDistinct` done ✅

I think we are missing this one in the README

**Comment by manchaary** [comment]
Hello guys! Thank you for starting this huge work on migrating such a useful library.

I want to contribute for this project but have I couple of questions.
I wanted to migrate very useful for me `useScroll` hook but it uses not yet migrated `useRafState` hook; 
1 - Do I have to migrate `useRafState` first or it is ok to use `useSafeState` instead?
2 - Project seems to have only `testing-library/react-hooks` and I really don't know how to write tests for `useScroll` hook in this case besides just having `should be defined` and `should render` cases. Is it ok if I will just add those two cases?

**Comment by matthew-dean** [comment]
Can you please re-visit removing `createMemo`? It's an extremely useful pattern that allows you to share a memoized function across components. https://github.com/streamich/react-use/blob/master/docs/createMemo.md

**Comment by Bailig** [comment]
Hello, I'm first time working on open source projects. I want to start with useError :)

**Comment by Bailig** [comment]
Hello, I finished the useError hook, but I couldn't start the storybook. I'm just wondering if it's a known issue?
```
yarn run v1.22.18
$ start-storybook -p 6006 --docs --no-manager-cache
info @storybook/react v6.4.22
info 
info => Loading presets
info => Serving static files from ././.storybook/public at /
ERR! TypeError: (intermediate value) is not iterable
ERR!     at _default (/node_modules/@storybook/builder-webpack4/dist/cjs/preview/iframe-webpack.config.js:73:22)
ERR!     at processTicksAndRejections (internal/process/task_queues.js:95:5)
ERR!     at async Object.start (/node_modules/@storybook/builder-webpack4/dist/cjs/index.js:91:16)
ERR!     at async Promise.all (index 0)
ERR!     at async storybookDevServer (/node_modules/@storybook/core-server/dist/cjs/dev-server.js:126:28)
ERR!     at async buildDevStandalone (/node_modules/@storybook/core-server/dist/cjs/build-dev.js:115:31)
ERR!     at async buildDev (/node_modules/@storybook/core-server/dist/cjs/build-dev.js:161:5)
ERR!  TypeError: (intermediate value) is not iterable
ERR!     at _default (/node_modules/@storybook/builder-webpack4/dist/cjs/preview/iframe-webpack.config.js:73:22)
ERR!     at processTicksAndRejections (internal/process/task_queues.js:95:5)
ERR!     at async Object.start (/node_modules/@storybook/builder-webpack4/dist/cjs/index.js:91:16)
ERR!     at async Promise.all (index 0)
ERR!     at async storybookDevServer (/node_modules/@storybook/core-server/dist/cjs/dev-server.js:126:28)
ERR!     at async buildDevStandalone (/node_modules/@storybook/core-server/dist/cjs/build-dev.js:115:31)
ERR!     at async buildDev (/node_modules/@storybook/core-server/dist/cjs/build-dev.js:161:5)
```

**Comment by JoeDuncko** [comment]
@Bailig Yes, Storybook being broken is a known issue. Dependabot broke something last week. Will try to fix it today. Sorry about that!

**Comment by jquintozamora** [comment]
Hey guys, 
I'd like to do migration from old `react-use`, the only remaining bit for me is `useBeforeUnload`. Do you have some estimation when will be migrated ? 

thanks!

**Comment by kylemh** [comment]
This is a relatively easy project to get involved with contributions! Maybe you'd be interested in opening a PR yourself for it?

**Comment by kylemh** [comment]
If we don't plan to implement `useBeforeUnload`, maybe we should strike it from OP?

**Comment by xobotyi** [comment]
surely do, just realized just now (list been made up before `useEventListener` implementation)

**Comment by xobotyi** [comment]
Overall you can make a PR with migration guide for taht hook (have not enough time for that atm)

**Comment by kylemh** [comment]
That being said, maybe there's something to be said for NOT porting this hook if it's so easy to accomplish with `useEventListener`

**Comment by xobotyi** [comment]
I'll mention it in the list later

**Comment by xobotyi** [comment]
@ArttuOll could you please make a mention to migration guide about unwilling to implement `useBeforeUnload` with example from above conversation?

**Comment by ArttuOll** [comment]
Updated the above list to match #1004 .

**Comment by ArttuOll** [comment]
I also ticked the ones that are not going to be implemented, so that they would also be counted as completed tasks.

**Comment by ArttuOll** [comment]
What does everybody think about porting of the location-related hooks such as `useHash`, `useLocation` and `useSearchParam`? There are quite a few routing libraries out there that also offer these hooks. Does it make sense for us to offer them as well?

Personally I think no 🤔

**Comment by kylemh** [comment]
I agree with you.

**Comment by xobotyi** [comment]
Just been thinking about it yesterday when used react-router's hook😁
Strike them out.

**Comment by xobotyi** [comment]
Also you can strike out `useRaf` as it is achievable via composition of `useRerender` and `useRafEffect`

**Comment by ArttuOll** [comment]
I presume `useUpsert` will not be ported, since `useList` already provides an upsert function. I ticked it off from the list and created a PR (#1046) to update the migration guide.

**Comment by jpwallace22** [comment]
Unless I'm missing something here, I feel like `useSize` can probably be crossed off. Since there is a `useMeasure` and `useResizeObserver`

**Comment by jpwallace22** [comment]
@ArttuOll I was looking at porting over `useTimeout` and `useTimeoutFn` next. `useTimeout` is pretty much just `useRerender` on a timer. Do you think it would be best to make that hook? Or what are your thoughts on just having an optional timer on `useRerender`?

**Comment by xobotyi** [comment]
I can't see the sense of porting `useTimeout` but `useTimeoutCallback` would be pretty much handy one, since it could be well composed with other hooks

**Comment by jpwallace22** [comment]
@xobotyi I was about to do it, but it looks like there is already a `useTimeoutEffect` that does it. Might want to check the box.

**Comment by ArttuOll** [comment]
Updated the list again.

**Comment by ArttuOll** [comment]
Ticked off `usePromise`, which will not be implemented, as decided in #1048 . Also ticked off `useLogger`, which has been implemented as `useLifecycleLogger` and `useRendersCount` which has been implemented as `useRenderCount`.

What does everybody think about porting of the following hooks:

- `useUnmountPromise` - Probably should not be ported, because it's almost the same as `usePromise`.
- `useShallowCompareEffect` - We already have `useDeepCompareEffect` and `useCustomCompareEffect`. Could be easily implemented.
- `useGetSet` - Could be useful for some functional programming stuff, but you could easily wrap the state setter into a function yourself `(value: A) => setState(value)`. Also the examples in `react-use` for this hook make it seem that this hook could be replaced with just functional state updates.
- `useSetState` - I feel like this hook is unsuitable for modern React (it emulates this.setState of class-based components).
- `useMethods` - Slight syntactic sugar over `useReducer`.

**Comment by xobotyi** [comment]
agreed on all of them

**Comment by tansanDOTeth** [comment]
For useTween, I would like to make suggestions for the API. It would be helpful if it can return a start function to grant control over when to start the tweening process.

**Comment by Frankcaozas** [comment]
can i work on useScrolling,  only the test is not done

**Comment by JoeDuncko** [comment]
> @JoeDuncko can i work on useScrolling,  only the test is not done

Sure!

**Comment by malavshah9** [comment]
@JoeDuncko  I would like to work on `useQueue`, can I start working on it?

**Comment by JoeDuncko** [comment]
> @JoeDuncko  I would like to work on `useQueue`, can I start working on it?

Sure!

**Comment by xobotyi** [comment]
@JoeDuncko dang it! we already have a queue hook, but it is missing from hooks listing🤦‍♂️

**Comment by JoeDuncko** [comment]
> @JoeDuncko dang it! we already have a queue hook, but it is missing from hooks listing🤦‍♂️

@xobotyi Ah crap, I can knock that out if no one else does tomorrow.

**Comment by malavshah9** [comment]
@JoeDuncko  @xobotyi 
I was just looking to work on `useCopyToClipboard`, but then found [this discussion](https://github.com/react-hookz/web/pull/883) where we have concluded that it is not needed at the moment. Can we remove this from this [list also](https://github.com/react-hookz/web/issues/33#issue-873958838), if we don't want to build it.

**Comment by malavshah9** [comment]
@JoeDuncko  @xobotyi 
Moreover, I am looking to work on `useSpeech` with the following definition, is this fine or do we want to improve here?

```typescript


type SpeechOptions = {
  lang: string;
  voice?: SpeechSynthesisVoice;
  rate: number;
  pitch: number;
  volume: number;
};
export type VoiceInfo = Pick<SpeechSynthesisVoice, 'lang' | 'name'>;

export type ISpeechState = SpeechOptions & {
  isPlaying: boolean;
  status: string;
  voiceInfo: VoiceInfo;
};

enum Status {
  init,
  play,
  pause,
  end,
}

const useSpeech = (text: string, options: ISpeechOptions): ISpeechState
```

Same as we have in `react-use`

**Comment by xobotyi** [comment]
@malavshah9 sold!

**Comment by malavshah9** [comment]
@xobotyi I wanted to work and port below mentioned hooks:
1. `useIdle`
2. `useRaf`
3. `useGeolocation`
4. `useStateList`

**Comment by xobotyi** [comment]
@malavshah9 it would be way better if youll help with tests migration so we can switch towards react 18

https://github.com/react-hookz/web/pull/1377

I will updatw that PR so it is containing only tests changes without, and after that youll be able to migrate tests

**Comment by malavshah9** [comment]
@xobotyi I would love to do that. Should I start migrating that for each hooks and giving you separate PR?

**Comment by I-Want-ToBelieve** [comment]
你好呀, 我想知道您出于什么考虑不实施 [useSetState](https://github.com/streamich/react-use/blob/master/docs/useSetState.md)  ?

**Comment by kylemh** [comment]
I personally think it's a poor idea. I am not in charge though!  I just think using such a shortener exposes people to risk in terms of memorization and unnecessary renders. I'd advocate instead to use `useReducer` or use separate `useState` hooks.

**Comment by xobotyi** [comment]
It is not implemented because there are a ton of possible strategies to merge objects.
Overall such functionality can be done in 2-3 extra rows of code on the user-side and therefore does not require to be implemented in the library.

**Comment by pedmeireles** [comment]
Hi there,

Is there anyone working on the [useStateList](https://github.com/streamich/react-use/blob/master/docs/useStateList.md) ?

If not, is there any place where I can assign interest to implement this hook? 
I'll take a look on the repo for the contributing guide on the meantime. Thanks in advance!

**Comment by samithahansaka** [comment]
Picking up `useBattery` from the list. Implementation is in #1667, rebased on current `master` with DOM and SSR tests.

Use case: letting an app degrade gracefully on a draining battery, pausing polling, prefetching or non-essential animation when `charging` is false and `level` is low, and surfacing a low-battery hint in installed PWAs. It is not something you can compose out of the existing hooks, since the Battery Status API is promise-based and needs its own event subscription and cleanup.
